
    var Alumnos = [
{
    Nombre: 'Angel Aldair',
    ApPaterno: 'Bárcenas',
    ApMaterno: 'Mora',
    Edad: 19,
    FechaNac: '21/07/2000',
    Sexo: 'M',
    },
{
    Nombre: 'Juan Pablo Javier',
    ApPaterno: 'García',
    ApMaterno: 'Castillo',
    Edad: 20,
    FechaNac: '07/06/1999',
    Sexo: 'M',
    },
 {
        Nombre: 'Guadalupe',
        ApPaterno: 'Hernández',
        ApMaterno: 'Sánchez',
        Edad: 25,
        FechaNac: '21/10/1994',
        Sexo: 'F',
    },
{
        Nombre: 'Guadalupe',
        ApPaterno: 'Limón',
        ApMaterno: 'Flores',
        Edad: 24,
        FechaNac: '06/10/1995',
        Sexo: 'F',
    },
{
        Nombre: 'Enrique Alejandro',
        ApPaterno: 'Castro',
        ApMaterno: 'González',
        Edad: 21,
        FechaNac: '07/06/1998',
        Sexo: 'H',
    },
{
        Nombre: 'Erick Martin',
        ApPaterno: 'Fernandez',
        ApMaterno: 'Jimenez',
        Edad: 20,
        FechaNac: '20/02/2000',
        Sexo: 'M',
    },
{
        Nombre: 'Juan Pablo',
        ApPaterno: 'Villanueva',
        ApMaterno: 'Pámanes',
        Edad: 21,
        FechaNac: '14/10/1998',
        Sexo: 'M',
    },
{
        Nombre: 'Darío André',
        ApPaterno: 'Alfaro',
        ApMaterno: 'Hernández',
        Edad: 23,
        FechaNac: '21/02/1997',
        Sexo: 'M',
    },
{
        Nombre: 'Kevin Fernando',
        ApPaterno: 'Navarro',
        ApMaterno: 'Garza',
        Edad: 23,
        FechaNac: '13/11/1996',
        Sexo: 'M',
    },
{
        Nombre: 'Elisa Paola',
        ApPaterno: 'Juárez',
        ApMaterno: 'Ávila',
        Edad: 20,
        FechaNac: '20/05/1999',
        Sexo: 'F',
    },
{
        Nombre: 'Nayeli Atzin',
        ApPaterno: 'Huerta',
        ApMaterno: 'Castañeda',
        Edad: 21,
        FechaNac: '25/08/1998',
        Sexo: 'F',
    }
];